version: "3.9"

services:

  db:
    image: postgres:15
    container_name: atomquest_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: surya_851973
      POSTGRES_DB: atomquest

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: .

    container_name: atomquest_backend
    restart: always

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:surya_851973@db:5432/atomquest

    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --workers 2

volumes:
  postgres_data: